In [2]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)



[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [3]:
#Dimension (x.ndim)
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)


1
2
3


In [4]:
#Shape (rows,column)
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(2, 2, 3)


In [5]:
#Data Type
import numpy as np
a.dtype


dtype('int64')

In [6]:
#Zeros
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#Ones
np.ones((3,2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
#Eye
np.eye((3))


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#arange
np.arange(1,10,5)


array([1, 6])

In [10]:
# arithmatic op
c = a*2
d = a+5
print(c)
print(d)

[2 4 6 8]
[6 7 8 9]


In [11]:
#Mean
np.mean(a)



np.float64(2.5)

In [12]:
#Median
np.median(a)

np.float64(2.5)

In [1]:
#Max
np.max(a)

NameError: name 'np' is not defined

In [13]:
print("a -> Mean:", np.mean(a), "Median:", np.median(a), "Max:", np.max(a))
print("b -> Mean:", np.mean(b), "Median:", np.median(b), "Max:", np.max(b))
print("c -> Mean:", np.mean(c), "Median:", np.median(c), "Max:", np.max(c))



a -> Mean: 2.5 Median: 2.5 Max: 4
b -> Mean: 3.5 Median: 3.5 Max: 6
c -> Mean: 5.0 Median: 5.0 Max: 8
